language: java
git:
  depth: false
matrix:
  include:
    - jdk: openjdk8
      env: PUBLISH="true"
    - jdk: openjdk9
      env: PUBLISH="false"
    - jdk: openjdk10
      env: PUBLISH="false"
    - jdk: openjdk11
      env: PUBLISH="false"
    - jdk: openjdk12
      env: PUBLISH="false"
    - jdk: openjdk13
      env: PUBLISH="false"
