reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
official_repo: &official_repo
  'Protelis/Protelis-KDoc-generator'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: xenial
stages:
  - check
  - test
  - deploy
env:
  global:
    - secure: "vF5CiE9oFPX0UepdmAou8uCajcQdccFaRcFKxO1KPWiVMYiSDaWjU+T1NxSWExLPpVty7YV9lSEPEZgNYlYtNyWkxANPDrVevbvvYBr5PyQ9PBDvCW5LSIPg8ywhHyEEaAkm0vzGfApCdVrKs1YsLjG6IQ1MUc0iNqKibdRS7AJfwWjtwhuxRNZ/BZtzSOLf7jHcc/0H7zq1quHFvKMcKzPNfuPJ3GkrLVFni9tOKAcfhlEtq9cOzKFbJDHY1Nh8vySJSEkTWMIYixsOo6nvTnnR3xBzE6Uxo1uE6CzN8ZSMSMmxTGg4KfXkp3wxFC/jWkYr2I4m1yil175TZ7MRvxlvcAFSvTDiw73UifdN5v6b8A4YLz3u7hx9CxPTBzFajPlRxxEXYR9UGSh27r4vStLTHiOWO+R37NJT70lpzTgO6C0KOk+lrzqpYwaN9d5txP7IhQfq5zFnTQDE6dWCRC370Dk2/WKrIZ4jSI+sw7mecqA8Aak+rrxz6EHCj6WZFmWx5YTnX9O446TTvsfR4yWm/p7jfadH3Gyv1uzl2kPrtXcGdPsCoiRrTGaC0sfp1SSDqEAl7fZrbCDFnyPHEs8qdPytfp0T2m4M8m9ypUvnY3TfAwMj8NaAYKrg1HtwY+XYH9T0LBCtOcaIz3mBAb7yeK1w9SgITk3BPa1oLXY="
    - secure: "tYVbhN2u51OgaaChHh6dvhn53TNrPfZfH5pHBlFbe0QjAzmJdMyTIcTl4JQnA/9Oy9zcwGA+B81qjo5qXWlp5xkFASIB+H+Njt3SPIGn+jYOez3At7TPvEOUL/h8YhpGp+TZxg0Et8uteC8bTbXrxm4pokAj0n8B65UqxQzH6xAYt9BwAZwSBUxTc7pAmW4YOdYnhb7wnFw+F2AW35edDnmPGPE9ztqoilCjlqGnFuQGwAgNPhmAEMt6xKUpKj5QHZrnooItH/uLYEtnTfflWzimLj3BMMCc/+kZxXa5jWARjffTAPWITB9TV9CBHodouDig9PBIB4c1P7jlsHM0KcZH3ZZsE/NMI8MmrgwdVqLFuLT9f0J9TYRVSB5j8rU+8+yX+iLW965ANgVs5zLx3Mhb8/U3KgxAK8T6lVUi+Wvt0YDG6sthhAUvQxA8oBDFnRLx1dSxCCViL7/YRi8uL7vgzjFV4CJ18LS3FWreEOrwa7hTp2MjdgIkByabdDU7JUQ5b/bal7dOswJ9wSLzOVaDQvBsZ/n1P9nMEuE3pIoeTM1njalRdi/Z68PYGUqJRe2bLnv7RRJTGpvQQ3Q0xK5Z1EC72UNPb2dpa3c86vXuL/u/qyyTKFjjW43hXSOUIwtz+YruKHH28+LXeVRwes2mn+GikSSVHFSLP06IzRU="
    - secure: "aHGOT4KDg0PVzE3Hd3+Z89Mf+e9cruNQ5WCbm8A1ecIgKRzwGARuijjCWHsBxOFxi4TrPv5q3QOS6urR2s0W2tIIXs21jBIiWWMowo7O5wIhqu/V5L/PeZUtq9ms8kvS8jjp5t6x895lNv1DVVzZ+oufjZsehzpyHmwb73Ks+vlDHRxucvBfNl9t1m1gh0Eem0J40adPVas/FmINcVsLWR9l3ICb8NBkwdfO/zdZCWUP+7VTCCTT/6CR2fib5ogErxYAv55NusiMQQiHYjgDPgOKX7vwEZq8VaqmLXjchqeYAdVbfQxL3PQVX/KmlpE3aK8GpISi+yWghy+kt5AyhASPhTyiq7GsW2riy22HIkOQu6znLOurQriVTfsjZZrS0CZqJz6tgxUnLB1pEoNVpg9ZrNF1ujUBTklOv3JVDmSSpXS/o+ylpm8Tv6Ql9tuymuj11YDFStu9ohR28s/VPyVTDRlqvjE7QusEtgfxQW9qcswCsM75i5mboex7oFgoW3bBhnEYhxGukSdRxXnhdGaXGPdd71EY2ROwBEuFGQEcbwP9uWIroOf272D/8h5yJXO+JXT2VtOuUCMWPWd8jYQCQC99WzlaKGQDb3hMJRWnk70xsGj8dXITBFQ9Hdfkbzt/MMhdTVZCZqzhsbCFb/FI+PFT5KyZ9sw/vF79xKo="
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - PUBLISH="false"
    - TERM=dumb
    - OFFICIAL_REPO_SLUG="Protelis/Protelis-KDoc-generator"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
    - JDK="adopt-openj9@1.12"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - ./gradlew clean check --scan --parallel
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_c3e4142aebb8_key -iv $encrypted_c3e4142aebb8_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
        - bash prepare_environment.sh
      script:
        - ./gradlew sign -x test --scan --parallel
      after_success:
        - ./gradlew publishPlugins
        - ./gradlew publish
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - ./gradlew clean test --scan --stacktrace
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
  - if $SHOULD_CONFIGURE && $PUBLISH; then ./gradlew publishPlugins; ./gradlew publish; fi
notifications:
  email:
    - danilo.pianini@unibo.it
    - roby.casadei@unibo.it
    - jake.beal@raytheon.com
